### ISSUE TITLE
Repeated xml_id for report template and action 

### ISSUE THREAD

**Issue by BT-dherreros** [hawalt/it-engineering#2]
https://github.com/hawalt/it-engineering/blob/83d11225877daed9737ab6b15e75916db672fe19/hg_dhl/reports/report.xml#L3
has the same id than https://github.com/hawalt/it-engineering/blob/83d11225877daed9737ab6b15e75916db672fe19/hg_dhl/reports/report.xml#L131 which causes duplicated reports and overwriting of views.
To fix we changed https://github.com/hawalt/it-engineering/blob/83d11225877daed9737ab6b15e75916db672fe19/hg_dhl/reports/report.xml#L131 to `id="action_report_hg_tracking"`.
We had to remove the duplicated reports and actions and then update.

**Comment by hawalt** [comment]
Thank for for the hint. I updated the code accordingly with my latest updates.
